<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DLLA1660" name="com.qainfotech.automation.tatocAutomation.Advance_Test" tests="6" failures="0" timestamp="2021-01-17T22:02:09 IST" time="20.797" errors="1">
  <testcase name="setupwebdriver" time="5.587" classname="com.qainfotech.automation.tatocAutomation.Advance_Test"/>
  <system-out/>
  <testcase name="launchQAITVPN" time="4.788" classname="com.qainfotech.automation.tatocAutomation.Advance_Test"/>
  <system-out/>
  <testcase name="launchtatoc" time="5.595" classname="com.qainfotech.automation.tatocAutomation.Advance_Test"/>
  <system-out/>
  <testcase name="AdvanceTest_Select" time="1.866" classname="com.qainfotech.automation.tatocAutomation.Advance_Test"/>
  <system-out/>
  <testcase name="HoverMenu" time="2.890" classname="com.qainfotech.automation.tatocAutomation.Advance_Test"/>
  <system-out/>
  <testcase name="dataBaseConnection" time="0.071" classname="com.qainfotech.automation.tatocAutomation.Advance_Test">
    <error type="java.lang.ClassNotFoundException" message="com.mysql.jdbc.Driver">
      <![CDATA[java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at com.qainfotech.automation.tatocAutomation.Advance_Test.dataBaseConnection(Advance_Test.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- dataBaseConnection -->
  <system-out/>
</testsuite> <!-- com.qainfotech.automation.tatocAutomation.Advance_Test -->
